/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: af5048b39bdd15cfcda2fa969fe0254c)
interface __BaseEnv_Env {
	REGISTERS: KVNamespace;
	ASSETS: Fetcher;
	RASTER_REGISTER: Workflow<Parameters<import("./worker/index").RasterRegisterWorkflow['run']>[0]['payload']>;
}
declare namespace Cloudflare {
	interface GlobalProps {
		mainModule: typeof import("./worker/index");
	}
	interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
